spring:
  resources:
    # 静态资源默认路径
    #spring.web.resources.static-locations=classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/
    # 手动修改后，⚠️注意，自定义目录下，如"myCustomizedStaticFolder"放"index.html"以及"favicon.ico"不能生效。除自定义，其他默认目录"/META-INF/resources/"、"/resources/"、"/static/"、"/public/"可生效
    static-locations: [classpath:/myCustomizedStaticFolder/, classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/]
    add-mappings: true # 默认true，若为false，则所有默认静态资源路径皆禁用了

  mvc:
    # 默认静态资源访问前缀 - spring.mvc.static-path-pattern=/**
    # 手动修改后 - static-path-pattern: /resources/**，便于拦截器排除静态资源拦截
    # 若修改静态资源访问前缀，则访问欢迎页只能是手动加前缀，spring不会帮你映射到根路径：http://localhost:8080/resources/index.html
#    static-path-pattern: /resources/**